name: Build Status

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v2.0.1
      with:
        version: "17.0.5"
        arch: x64

    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Create build directory
      run: cmake -E make_directory build

    - name: Configure
      working-directory: ${{github.workspace}}/build
      run: cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE

